name: desmosdemo
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  dependencies: ^0.1.5
  equatable: ^1.0.1
  flutter_bloc: ^2.0.1
  flutter_screenutil: ^0.6.1
  font_awesome_flutter: ^8.5.0
  meta: ">=1.1.0 <2.0.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true