name: mooncake
description: A decentralized Twitter based on Desmos
version: 0.0.1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bip39:
  collection:
  cupertino_icons:
  dependencies:
  emoji_picker:
  equatable:
  flutter_bloc:
  flutter_markdown:
  flutter_screenutil:
  flutter_secure_storage:
  flutter_svg:
  font_awesome_flutter:
  intl:
  json_annotation:
  json_serializable:
  meta:
  path_provider:
  alan:
    git: https://github.com/alan-sdk/alan.dart
  sembast:
  shared_preferences:
  stream_transform: any
  web_socket_channel:

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Dosis-Light.ttf
          weight: 200
        - asset: assets/fonts/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dosis-ExtraBold.ttf
          weight: 800