name: dwitter
description: A decentralized Twitter based on Desmos
version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bip39: ^1.0.3
  cupertino_icons: ^0.1.3
  dependencies:
  equatable: ^1.0.2
  flutter_bloc: ^3.1.0
  flutter_screenutil: ^1.0.1
  flutter_secure_storage: ^3.3.1+1
  font_awesome_flutter: ^8.5.0
  json_annotation: ^3.0.1
  json_serializable: ^3.2.5
  meta: ">=1.1.0 <2.0.0"
  path_provider: ^1.5.1
  alan:
    git: https://github.com/alan-sdk/alan.dart
  sembast: ^2.1.2+3
  shared_preferences: ^0.5.6
  stream_transform: any
  web_socket_channel: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true