name: mooncake
description: A decentralized Twitter based on Desmos
version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bip39:
  cupertino_icons:
  dependencies:
  equatable:
  flutter_bloc:
  flutter_screenutil:
  flutter_secure_storage:
  font_awesome_flutter:
  intl:
  json_annotation:
  json_serializable:
  meta:
  path_provider:
  alan:
    git: https://github.com/alan-sdk/alan.dart
  sembast:
  shared_preferences:
  stream_transform: any
  web_socket_channel:

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true