name: mooncake
description: A decentralized Twitter based on Desmos
version: 0.0.11

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  alan:
    git:
      url: git://github.com/alan-sdk/alan.dart.git
      ref: cosmos-v0.38.0
  bip39:
  cloud_firestore:
  collection:
  cupertino_icons:
  dependencies:
  emoji_picker:
  equatable:
  firebase_core:
  firebase_analytics:
  firebase_auth:
  firebase_messaging:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_local_notifications:
  flutter_markdown:
  flutter_screenutil:
  flutter_secure_storage:
  flutter_svg:
  font_awesome_flutter:
  http:
  image_picker:
  intl:
  json_annotation:
  json_serializable:
  meta:
  mime_type:
  path_provider:
  rxdart:
  sembast:
  sentry:
  shared_preferences:
  stream_transform:
  timeago:
  url_launcher:
  web_socket_channel:

dev_dependencies:
  build_runner:
  bloc_test:
  flutter_test:
    sdk: flutter
  mockito:
  mock_web_server:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Dosis
      fonts:
        - asset: assets/fonts/Dosis-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Dosis-Light.ttf
          weight: 200
        - asset: assets/fonts/Dosis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dosis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dosis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Dosis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Dosis-ExtraBold.ttf
          weight: 800
