name: desmosdemo
description: A decentralized Twitter based on Desmos
version: 0.1.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  dependencies: ^0.1.5
  equatable: ^0.5.0
  flutter_bloc: ^2.0.1
  flutter_screenutil: ^0.6.1
  font_awesome_flutter: ^8.5.0
  json_annotation: ^3.0.0
  json_serializable: ^3.2.3
  meta: ">=1.1.0 <2.0.0"
  path_provider: ^1.4.5
  sacco: ^0.0.13
  web_socket_channel: ^1.1.0
  workmanager: ^0.1.5

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^1.7.2

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true