version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:v1.5.8

    branches:
      only: master

    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - run:
          name: Run Flutter foramt
          command: flutter format . --dry-run
      - run:
          name: Run the application tests
          command: flutter test test

# TODO: Add this once we find out how to include the proper signing data
#      - run:
#          name: Build the Android version
#          command: flutter build apk
#      - store_artifacts:
#          path: build/app/outputs/apk/release/app-release.apk