version: 2.1

executors:
  flutter:
    docker:
      - image: cirrusci/flutter:v1.5.8

jobs:
  test:
    executor: flutter
    steps:
      - checkout
      - run:
          name: Run Flutter doctor
          command: flutter doctor
      - run:
          name: Run Flutter format
          command: flutter format --dry-run .
      - run:
          name: Run the application tests
          command: flutter test test

workflows:
  version: 2
  test-suite:
    jobs:
      - test
          filters:
            branches:
              ignore:
                - gh-pages